name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Build for production
      run: npm run build
      env:
        NODE_ENV: production
        VITE_API_URL: https://sairaj-travels-backend.onrender.com
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
        
    - name: Deploy to Render (if main branch)
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Build completed successfully!"
        echo "Ready for deployment to Render.com"
